-- MySQL Script generated by MySQL Workbench
-- Thu Dec  5 15:06:50 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Farm
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Farm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Farm` DEFAULT CHARACTER SET utf8 ;
USE `Farm` ;

-- -----------------------------------------------------
-- Table `Farm`.`location_warehouse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Farm`.`location_warehouse` ;

CREATE TABLE IF NOT EXISTS `Farm`.`location_warehouse` (
  `loction` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`loction`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Farm`.`Warehouse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Farm`.`Warehouse` ;

CREATE TABLE IF NOT EXISTS `Farm`.`Warehouse` (
  `C_id` INT NOT NULL,
  `Amount` INT NOT NULL,
  `location` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`C_id`, `location`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Farm`.`Worker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Farm`.`Worker` ;

CREATE TABLE IF NOT EXISTS `Farm`.`Worker` (
  `W_id` INT NOT NULL AUTO_INCREMENT,
  `W_name` VARCHAR(40) NOT NULL,
  `Start_date` DATE NOT NULL,
  `Salary` INT NOT NULL,
  `W_sex` CHAR(3) NOT NULL,
  `W_Bdate` DATE NOT NULL,
  `Phone` INT NOT NULL,
  `Email` VARCHAR(50) NOT NULL,
  `Farm_id` INT NOT NULL,
  `Warehouse_C_id` INT NOT NULL,
  PRIMARY KEY (`W_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Farm`.`Farm`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Farm`.`Farm` ;

CREATE TABLE IF NOT EXISTS `Farm`.`Farm` (
  `F_id` INT NOT NULL,
  `F_bank_account` INT NOT NULL,
  `F_location` VARCHAR(30) NOT NULL,
  `Manager_id` INT NOT NULL,
  PRIMARY KEY (`F_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Farm`.`Machine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Farm`.`Machine` ;

CREATE TABLE IF NOT EXISTS `Farm`.`Machine` (
  `Ma_id` INT NOT NULL,
  `Type` VARCHAR(20) NOT NULL,
  `F_id` INT NOT NULL,
  PRIMARY KEY (`Ma_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Farm`.`Crops`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Farm`.`Crops` ;

CREATE TABLE IF NOT EXISTS `Farm`.`Crops` (
  `C_id` VARCHAR(50) NOT NULL,
  `C_name` VARCHAR(30) NOT NULL,
  `C_category` VARCHAR(30) NOT NULL,
  `Amount` INT NOT NULL,
  `F_id` INT NOT NULL,
  `Ma_id` INT NOT NULL,
  `Warehouse_C_id` INT NOT NULL,
  `Warehouse_location` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`C_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Farm`.`Merchant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Farm`.`Merchant` ;

CREATE TABLE IF NOT EXISTS `Farm`.`Merchant` (
  `M_id` INT NOT NULL,
  `M_name` VARCHAR(45) NOT NULL,
  `M_sex` CHAR(3) NOT NULL,
  `M_bank_account` INT NOT NULL,
  `Phone` INT NOT NULL,
  `Email` VARCHAR(50) NOT NULL,
  `Warehouse_Location` VARCHAR(30) NOT NULL,
  `C_id` INT NOT NULL,
  PRIMARY KEY (`M_id`),
  UNIQUE INDEX `M_bank_account_UNIQUE` (`M_bank_account` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Farm`.`Bank`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Farm`.`Bank` ;

CREATE TABLE IF NOT EXISTS `Farm`.`Bank` (
  `B_id` INT NOT NULL,
  `B_name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`B_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Farm`.`Supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Farm`.`Supplier` ;

CREATE TABLE IF NOT EXISTS `Farm`.`Supplier` (
  `S_id` INT NOT NULL,
  `S_name` VARCHAR(45) NOT NULL,
  `S_sex` CHAR(3) NOT NULL,
  `S_address` VARCHAR(45) NOT NULL,
  `Phone` INT NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`S_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Farm`.`Pesticide`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Farm`.`Pesticide` ;

CREATE TABLE IF NOT EXISTS `Farm`.`Pesticide` (
  `P_id` INT NOT NULL,
  `P_name` VARCHAR(45) NOT NULL,
  `Category` VARCHAR(45) NOT NULL,
  `Amount` INT NOT NULL,
  `Sup_id` INT NOT NULL,
  PRIMARY KEY (`P_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Farm`.`Dependent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Farm`.`Dependent` ;

CREATE TABLE IF NOT EXISTS `Farm`.`Dependent` (
  `D_name` VARCHAR(35) NOT NULL,
  `W_id` INT NOT NULL,
  `Sex` CHAR(3) NOT NULL,
  `Phone` INT NOT NULL,
  `Relationship` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`D_name`, `W_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Farm`.`land`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Farm`.`land` ;

CREATE TABLE IF NOT EXISTS `Farm`.`land` (
  `land_id` INT NOT NULL,
  `land_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`land_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Farm`.`Seeds`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Farm`.`Seeds` ;

CREATE TABLE IF NOT EXISTS `Farm`.`Seeds` (
  `S_id` INT NOT NULL,
  `S_name` VARCHAR(45) NOT NULL,
  `Category` VARCHAR(45) NOT NULL,
  `Amount` INT NOT NULL,
  `Sup_id` INT NOT NULL,
  `land_id` INT NOT NULL,
  PRIMARY KEY (`S_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Farm`.`Money_collected`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Farm`.`Money_collected` ;

CREATE TABLE IF NOT EXISTS `Farm`.`Money_collected` (
  `F_id` INT NOT NULL,
  `B_id` INT NOT NULL,
  `Date_of_coll` DATE NOT NULL,
  PRIMARY KEY (`F_id`, `B_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Farm`.`Bank_location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Farm`.`Bank_location` ;

CREATE TABLE IF NOT EXISTS `Farm`.`Bank_location` (
  `B_id` INT NOT NULL,
  `Blocation` VARCHAR(35) NOT NULL,
  PRIMARY KEY (`B_id`, `Blocation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Farm`.`Fodder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Farm`.`Fodder` ;

CREATE TABLE IF NOT EXISTS `Farm`.`Fodder` (
  `Fo_id` INT NOT NULL,
  `Amount` INT NOT NULL,
  `Ma_id` INT NOT NULL,
  `Location` VARCHAR(30) NOT NULL,
  `C_id` INT NOT NULL,
  PRIMARY KEY (`Fo_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Farm`.`Poultry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Farm`.`Poultry` ;

CREATE TABLE IF NOT EXISTS `Farm`.`Poultry` (
  `P_id` INT NOT NULL,
  `Sex` CHAR(3) NOT NULL,
  `F_id` INT NOT NULL,
  `Ma_id` INT NOT NULL,
  `land_id` INT NOT NULL,
  `Fodder_Fo_id` INT NOT NULL,
  PRIMARY KEY (`P_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Farm`.`Livestock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Farm`.`Livestock` ;

CREATE TABLE IF NOT EXISTS `Farm`.`Livestock` (
  `L_id` INT NOT NULL,
  `Sex` CHAR(3) NOT NULL,
  `F_id` INT NOT NULL,
  `Ma_id` INT NOT NULL,
  `land_id` INT NOT NULL,
  `Fodder_Fo_id` INT NOT NULL,
  PRIMARY KEY (`L_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Farm`.`anemal_sex`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Farm`.`anemal_sex` ;

CREATE TABLE IF NOT EXISTS `Farm`.`anemal_sex` (
  `id_ssex` INT NOT NULL,
  `sex` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_ssex`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Farm`.`anemal_sex_has_Livestock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Farm`.`anemal_sex_has_Livestock` ;

CREATE TABLE IF NOT EXISTS `Farm`.`anemal_sex_has_Livestock` (
  `id_sex` INT NOT NULL,
  `L_id` INT NOT NULL,
  PRIMARY KEY (`id_sex`, `L_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Farm`.`anemal_sex_has_Poultry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Farm`.`anemal_sex_has_Poultry` ;

CREATE TABLE IF NOT EXISTS `Farm`.`anemal_sex_has_Poultry` (
  `id-sex` INT NOT NULL,
  `P_id` INT NOT NULL,
  PRIMARY KEY (`id-sex`, `P_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Farm`.`anemal_prodact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Farm`.`anemal_prodact` ;

CREATE TABLE IF NOT EXISTS `Farm`.`anemal_prodact` (
  `id_prodacts` INT NOT NULL,
  `type_prodacts` VARCHAR(45) NOT NULL,
  `Ma_id` INT NOT NULL,
  `Warehouse_Location` VARCHAR(30) NOT NULL,
  `Warehouse_C_id` INT NOT NULL,
  PRIMARY KEY (`id_prodacts`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Farm`.`collected_from`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Farm`.`collected_from` ;

CREATE TABLE IF NOT EXISTS `Farm`.`collected_from` (
  `M_id` INT NOT NULL,
  `F_id` INT NOT NULL,
  `B_id` INT NOT NULL,
  PRIMARY KEY (`M_id`, `F_id`, `B_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `Farm`.`Worker`
-- -----------------------------------------------------
START TRANSACTION;
USE `Farm`;
INSERT INTO worker (W_id, W_name, Start_date, Salary, W_sex, W_Bdate, Phone, Email, Farm_id, Warehouse_C)
VALUES
(1, 'John Doe', '2024-01-10', 2500, 'M', '1985-06-15', 1234567890, 'john.doe@example.com', 101, 500),
(2, 'Jane Smith', '2023-12-01', 2700, 'F', '1990-03-25', 1234567891, 'jane.smith@example.com', 102, 450),
(3, 'Michael Johnson', '2024-02-05', 2900, 'M', '1980-11-10', 1234567892, 'michael.johnson@example.com', 103, 600),
(4, 'Emily Davis', '2024-03-18', 2600, 'F', '1988-07-12', 1234567893, 'emily.davis@example.com', 101, 550),
(5, 'David Brown', '2024-04-22', 2800, 'M', '1982-05-30', 1234567894, 'david.brown@example.com', 104, 470),
(6, 'Sarah Wilson', '2024-05-17', 3000, 'F', '1992-09-09', 1234567895, 'sarah.wilson@example.com', 102, 520),
(7, 'James Miller', '2024-06-01', 3100, 'M', '1979-02-18', 1234567896, 'james.miller@example.com', 103, 480),
(8, 'Linda Taylor', '2024-07-14', 3200, 'F', '1983-12-23', 1234567897, 'linda.taylor@example.com', 104, 530),
(9, 'Robert Anderson', '2024-08-06', 3300, 'M', '1991-04-02', 1234567898, 'robert.anderson@example.com', 101, 600),
(10, 'Patricia Thomas', '2024-09-13', 3400, 'F', '1990-01-19', 1234567899, 'patricia.thomas@example.com', 102, 510),
(11, 'Daniel Harris', '2024-01-21', 2500, 'M', '1987-11-11', 1234567801, 'daniel.harris@example.com', 101, 550),
(12, 'Sophia Clark', '2024-02-10', 2800, 'F', '1993-03-15', 1234567802, 'sophia.clark@example.com', 102, 480),
(13, 'Ethan Lewis', '2024-03-05', 2900, 'M', '1980-12-10', 1234567803, 'ethan.lewis@example.com', 103, 600),
(14, 'Isabella Walker', '2024-04-15', 2700, 'F', '1991-06-22', 1234567804, 'isabella.walker@example.com', 104, 500),
(15, 'Alexander Harris', '2024-05-20', 3100, 'M', '1985-04-18', 1234567805, 'alexander.harris@example.com', 101, 540),
(16, 'Mia Young', '2024-06-10', 3000, 'F', '1994-08-30', 1234567806, 'mia.young@example.com', 102, 490),
(17, 'Benjamin Hall', '2024-07-05', 3200, 'M', '1992-05-16', 1234567807, 'benjamin.hall@example.com', 103, 550),
(18, 'Charlotte Allen', '2024-08-25', 3300, 'F', '1989-02-14', 1234567808, 'charlotte.allen@example.com', 104, 560),
(19, 'Oliver King', '2024-09-12', 3400, 'M', '1986-09-28', 1234567809, 'oliver.king@example.com', 101, 600),
(20, 'Amelia Scott', '2024-10-17', 3500, 'F', '1995-07-19', 1234567810, 'amelia.scott@example.com', 102, 580),
(21, 'Lucas Green', '2024-11-05', 2500, 'M', '1987-12-22', 1234567811, 'lucas.green@example.com', 103, 500),
(22, 'Zoe Adams', '2024-12-01', 2600, 'F', '1991-04-17', 1234567812, 'zoe.adams@example.com', 104, 470),
(23, 'Henry Martinez', '2024-01-12', 2700, 'M', '1989-08-25', 1234567813, 'henry.martinez@example.com', 101, 510),
(24, 'Chloe Rodriguez', '2024-02-01', 2800, 'F', '1993-05-19', 1234567814, 'chloe.rodriguez@example.com', 102, 520),
(25, 'Samuel Moore', '2024-03-10', 2900, 'M', '1990-11-03', 1234567815, 'samuel.moore@example.com', 103, 530),
(26, 'Harper Perez', '2024-04-12', 3000, 'F', '1988-01-14', 1234567816, 'harper.perez@example.com', 104, 540),
(27, 'Jack Wilson', '2024-05-02', 3100, 'M', '1982-07-20', 1234567817, 'jack.wilson@example.com', 101, 550),
(28, 'Grace Johnson', '2024-06-22', 3200, 'F', '1986-02-05', 1234567818, 'grace.johnson@example.com', 102, 560),
(29, 'Aiden Carter', '2024-07-15', 3300, 'M', '1990-12-02', 1234567819, 'aiden.carter@example.com', 103, 570),
(30, 'Lily Nelson', '2024-08-04', 3400, 'F', '1995-04-23', 1234567820, 'lily.nelson@example.com', 104, 580),
(31, 'William Lee', '2024-09-03', 3500, 'M', '1981-03-27', 1234567821, 'william.lee@example.com', 101, 590),
(32, 'Eva Moore', '2024-10-20', 2600, 'F', '1994-11-10', 1234567822, 'eva.moore@example.com', 102, 500),
(33, 'James Harris', '2024-11-17', 2700, 'M', '1987-06-16', 1234567823, 'james.harris@example.com', 103, 510),
(34, 'Emma Young', '2024-12-12', 2800, 'F', '1992-08-14', 1234567824, 'emma.young@example.com', 104, 520),
(35, 'Oliver White', '2024-01-01', 2900, 'M', '1989-03-09', 1234567825, 'oliver.white@example.com', 101, 530),
(36, 'Scarlett King', '2024-02-15', 3000, 'F', '1993-12-25', 1234567826, 'scarlett.king@example.com', 102, 540),
(37, 'Samuel Green', '2024-03-01', 3100, 'M', '1992-06-02', 1234567827, 'samuel.green@example.com', 103, 550),
(38, 'Ella Lewis', '2024-04-30', 3200, 'F', '1995-01-18', 1234567828, 'ella.lewis@example.com', 104, 560),
(39, 'Caleb Clark', '2024-05-14', 3300, 'M', '1988-10-11
COMMIT;


-- -----------------------------------------------------
-- Data for table `Farm`.`anemal_sex`
-- -----------------------------------------------------
START TRANSACTION;
USE `Farm`;
INSERT INTO farm (F_id, F_bank_account, F_location, Manager_id) 
VALUES
(101, 123456789, 'Location A', 1),
(102, 987654321, 'Location B', 2),
(103, 112233445, 'Location C', 3),
(104, 667788990, 'Location D', 4),
(105, 555666777, 'Location E', 5),
(106, 444555666, 'Location F', 6),
(107, 333444555, 'Location G', 7),
(108, 222333444, 'Location H', 8),
(109, 111222333, 'Location I', 9),
(110, 999888777, 'Location J', 10),
(111, 888777666, 'Location K', 11),
(112, 777666555, 'Location L', 12),
(113, 666555444, 'Location M', 13),
(114, 555444333, 'Location N', 14),
(115, 444333222, 'Location O', 15),
(116, 333222111, 'Location P', 16),
(117, 222111000, 'Location Q', 17),
(118, 111000999, 'Location R', 18),
(119, 100999888, 'Location S', 19),
(120, 199888777, 'Location T', 20),
(121, 288777666, 'Location U', 21),
(122, 377666555, 'Location V', 22),
(123, 466555444, 'Location W', 23),
(124, 555444333, 'Location X', 24),
(125, 644333222, 'Location Y', 25),
(126, 733222111, 'Location Z', 26),
(127, 822111000, 'Location AA', 27),
(128, 911000999, 'Location AB', 28),
(129, 100999888, 'Location AC', 29),
(130, 199888777, 'Location AD', 30),
(131, 288777666, 'Location AE', 31),
(132, 377666555, 'Location AF', 32),
(133, 466555444, 'Location AG', 33),
(134, 555444333, 'Location AH', 34),
(135, 644333222, 'Location AI', 35),
(136, 733222111, 'Location AJ', 36),
(137, 822111000, 'Location AK', 37),
(138, 911000999, 'Location AL', 38),
(139, 100999888, 'Location AM', 39),
(140, 199888777, 'Location AN', 40),
(141, 288777666, 'Location AO', 41),
(142, 377666555, 'Location AP', 42),
(143, 466555444, 'Location AQ', 43),
(144, 555444333, 'Location AR', 44),
(145, 644333222, 'Location AS', 45),
(146, 733222111, 'Location AT', 46),
(147, 822111000, 'Location AU', 47),
(148, 911000999, 'Location AV', 48),
(149, 100999888, 'Location AW', 49),
(150, 199888777, 'Location AX', 50),
(151, 288777666, 'Location AY', 51),
(152, 377666555, 'Location AZ', 52),
(153, 466555444, 'Location BA', 53),
(154, 555444333, 'Location BB', 54),
(155, 644333222, 'Location BC', 55),
(156, 733222111, 'Location BD', 56),
(157, 822111000, 'Location BE', 57),
(158, 911000999, 'Location BF', 58),
(159, 100999888, 'Location BG', 59),
(160, 199888777, 'Location BH', 60);
COMMIT;


-- -----------------------------------------------------
-- Data for table `Farm`.`anemal_prodact`
-- -----------------------------------------------------
START TRANSACTION;
USE `Farm`;
IINSERT INTO Dependent (D_name, W_id, Sex, Phone, Relationship)
VALUES
('John Doe', 1, 'M', 1234567890, 'Friend'),
('Jane Smith', 2, 'F', 1234567891, 'Sister'),
('Michael Johnson', 3, 'M', 1234567892, 'Brother'),
('Emily Davis', 4, 'F', 1234567893, 'Cousin'),
('David Brown', 5, 'M', 1234567894, 'Friend'),
('Sarah Wilson', 6, 'F', 1234567895, 'Mother'),
('James Miller', 7, 'M', 1234567896, 'Father'),
('Linda Taylor', 8, 'F', 1234567897, 'Aunt'),
('Robert Anderson', 9, 'M', 1234567898, 'Uncle'),
('Patricia Thomas', 10, 'F', 1234567899, 'Friend'),
('Andrew Scott', 11, 'M', 1234567800, 'Brother'),
('Natalie Harris', 12, 'F', 1234567801, 'Cousin'),
('Kevin Clark', 13, 'M', 1234567802, 'Father'),
('Laura Lewis', 14, 'F', 1234567803, 'Mother'),
('George Walker', 15, 'M', 1234567804, 'Friend'),
('Olivia Hall', 16, 'F', 1234567805, 'Sister'),
('Isaac Young', 17, 'M', 1234567806, 'Brother'),
('Sophia Allen', 18, 'F', 1234567807, 'Friend'),
('Ethan King', 19, 'M', 1234567808, 'Cousin'),
('Emma Carter', 20, 'F', 1234567809, 'Aunt'),
('Lucas Mitchell', 21, 'M', 1234567810, 'Uncle'),
('Mason Rodriguez', 22, 'M', 1234567811, 'Father'),
('Harper Martinez', 23, 'F', 1234567812, 'Mother'),
('Liam Gonzalez', 24, 'M', 1234567813, 'Brother'),
('Zoe Perez', 25, 'F', 1234567814, 'Sister'),
('Henry Thomas', 26, 'M', 1234567815, 'Friend'),
('Ava Jackson', 27, 'F', 1234567816, 'Mother'),
('Jackie White', 28, 'F', 1234567817, 'Friend'),
('Charlotte Harris', 29, 'F', 1234567818, 'Cousin'),
('Alexander Scott', 30, 'M', 1234567819, 'Uncle'),
('Madison Lee', 31, 'F', 1234567820, 'Aunt'),
('Benjamin Lewis', 32, 'M', 1234567821, 'Father'),
('Ella Robinson', 33, 'F', 1234567822, 'Mother'),
('Daniel Young', 34, 'M', 1234567823, 'Brother'),
('Sophia Mitchell', 35, 'F', 1234567824, 'Sister'),
('William Turner', 36, 'M', 1234567825, 'Friend'),
('Lily Adams', 37, 'F', 1234567826, 'Aunt'),
('Jacob Nelson', 38, 'M', 1234567827, 'Cousin'),
('Mia Phillips', 39, 'F', 1234567828, 'Friend'),
('James Lewis', 40, 'M', 1234567829, 'Brother'),
('Amelia Carter', 41, 'F', 1234567830, 'Sister'),
('Matthew Walker', 42, 'M', 1234567831, 'Father'),
('Grace King', 43, 'F', 1234567832, 'Mother'),
('William Scott', 44, 'M', 1234567833, 'Cousin'),
('Natalie Adams', 45, 'F', 1234567834, 'Aunt'),
('Lucas Thomas', 46, 'M', 1234567835, 'Brother'),
('Chloe Perez', 47, 'F', 1234567836, 'Sister'),
('Evan Mitchell', 48, 'M', 1234567837, 'Friend'),
('Isabella Walker', 49, 'F', 1234567838, 'Mother'),
('Jameson Harris', 50, 'M', 1234567839, 'Father'),
('Lily Lewis', 51, 'F', 1234567840, 'Brother'),
('Sophia Walker', 52, 'F', 1234567841, 'Sister'),
('Harper Nelson', 53, 'F', 1234567842, 'Cousin'),
('William Scott', 54, 'M', 1234567843, 'Friend'),
('Madison Robinson', 55, 'F', 1234567844, 'Aunt'),
('James Thomas', 56, 'M', 1234567845, 'Uncle'),
('Lucas Carter', 57, 'M', 1234567846, 'Father'),
('Ella Gonzalez', 58, 'F', 1234567847, 'Mother'),
('Benjamin Phillips', 59, 'M', 1234567848, 'Brother'),
('Chloe Robinson', 60, 'F', 1234567849, 'Sister');
COMMIT;


START TRANSACTION;
USE `Farm`;
INSERT INTO machine (Ma_id, Type, F_id)
VALUES
(1, 'Tractor', 101),
(2, 'Harvester', 102),
(3, 'Plow', 103),
(4, 'Irrigation System', 101),
(5, 'Mower', 104),
(6, 'Seeder', 102),
(7, 'Sprayer', 103),
(8, 'Tiller', 101),
(9, 'Cultivator', 104),
(10, 'Baler', 102),
(11, 'Lifter', 103),
(12, 'Loader', 104),
(13, 'Excavator', 101),
(14, 'Forklift', 102),
(15, 'Combine', 103),
(16, 'Trencher', 101),
(17, 'Grader', 104),
(18, 'Digger', 102),
(19, 'Backhoe', 103),
(20, 'Roller', 101),
(21, 'Water Tanker', 104),
(22, 'Wheel Loader', 102),
(23, 'Grape Picker', 103),
(24, 'Cotton Picker', 101),
(25, 'Mini Excavator', 104),
(26, 'Scraper', 102),
(27, 'Farm Truck', 103),
(28, 'Towing Tractor', 101),
(29, 'Milling Machine', 104),
(30, 'Dump Truck', 102),
(31, 'Road Roller', 103),
(32, 'Snow Plow', 101),
(33, 'Bale Wrapper', 104),
(34, 'Grain Cart', 102),
(35, 'Plow Truck', 103),
(36, 'Windrower', 101),
(37, 'Chisel Plow', 104),
(38, 'Field Cultivator', 102),
(39, 'Row Crop Tractor', 103),
(40, 'Land Leveler', 101),
(41, 'Hay Rake', 104),
(42, 'Swather', 102),
(43, 'Grain Cart', 103),
(44, 'Soil Compactor', 101),
(45, 'Ag Tractor', 104),
(46, 'Trencher', 102),
(47, 'Field Sprayer', 103),
(48, 'Garden Tractor', 101),
(49, 'Windrower', 104),
(50, 'Cattle Feeder', 102),
(51, 'Subsoiler', 103),
(52, 'Farm Trailer', 101),
(53, 'Riding Mower', 104),
(54, 'Soil Aerator', 102),
(55, 'Vegetable Harvester', 103),
(56, 'Baling Twine', 101),
(57, 'Fertilizer Spreader', 104),
(58, 'Tree Planter', 102),
(59, 'Mulcher', 103),
(60, 'Ditcher', 101);
COMMIT;

sTART TRANSACTION;
USE `Farm`;
INSERT INTO poultry (PP_id, Sex, F_id, Ma_id, land_id, Fodder_Fo_id)
VALUES
(1, 'M', 101, 1, 201, 301),
(2, 'F', 102, 2, 202, 302),
(3, 'M', 103, 3, 203, 303),
(4, 'F', 104, 4, 204, 304),
(5, 'M', 101, 5, 205, 305),
(6, 'F', 102, 6, 206, 306),
(7, 'M', 103, 7, 207, 307),
(8, 'F', 104, 8, 208, 308),
(9, 'M', 101, 9, 209, 309),
(10, 'F', 102, 10, 210, 310),
(11, 'M', 103, 11, 211, 311),
(12, 'F', 104, 12, 212, 312),
(13, 'M', 101, 13, 213, 313),
(14, 'F', 102, 14, 214, 314),
(15, 'M', 103, 15, 215, 315),
(16, 'F', 104, 16, 216, 316),
(17, 'M', 101, 17, 217, 317),
(18, 'F', 102, 18, 218, 318),
(19, 'M', 103, 19, 219, 319),
(20, 'F', 104, 20, 220, 320),
(21, 'M', 101, 21, 221, 321),
(22, 'F', 102, 22, 222, 322),
(23, 'M', 103, 23, 223, 323),
(24, 'F', 104, 24, 224, 324),
(25, 'M', 101, 25, 225, 325),
(26, 'F', 102, 26, 226, 326),
(27, 'M', 103, 27, 227, 327),
(28, 'F', 104, 28, 228, 328),
(29, 'M', 101, 29, 229, 329),
(30, 'F', 102, 30, 230, 330),
(31, 'M', 103, 31, 231, 331),
(32, 'F', 104, 32, 232, 332),
(33, 'M', 101, 33, 233, 333),
(34, 'F', 102, 34, 234, 334),
(35, 'M', 103, 35, 235, 335),
(36, 'F', 104, 36, 236, 336),
(37, 'M', 101, 37, 237, 337),
(38, 'F', 102, 38, 238, 338),
(39, 'M', 103, 39, 239, 339),
(40, 'F', 104, 40, 240, 340),
(41, 'M', 101, 41, 241, 341),
(42, 'F', 102, 42, 242, 342),
(43, 'M', 103, 43, 243, 343),
(44, 'F', 104, 44, 244, 344),
(45, 'M', 101, 45, 245, 345),
(46, 'F', 102, 46, 246, 346),
(47, 'M', 103, 47, 247, 347),
(48, 'F', 104, 48, 248, 348),
(49, 'M', 101, 49, 249, 349),
(50, 'F', 102, 50, 250, 350),
(51, 'M', 103, 51, 251, 351),
(52, 'F', 104, 52, 252, 352),
(53, 'M', 101, 53, 253, 353),
(54, 'F', 102, 54, 254, 354),
(55, 'M', 103, 55, 255, 355),
(56, 'F', 104, 56, 256, 356),
(57, 'M', 101, 57, 257, 357),
(58, 'F', 102, 58, 258, 358),
(59, 'M', 103, 59, 259, 359),
(60, 'F', 104, 60, 260, 360);
COMMIT;

sTART TRANSACTION;
USE `Farm`;
INSERT INTO livestock (Lid, Sex, F_id, Ma_id, land_id, Fodder_Fo_id)
VALUES
(1, 'M', 101, 1, 201, 301),
(2, 'F', 102, 2, 202, 302),
(3, 'M', 103, 3, 203, 303),
(4, 'F', 104, 4, 204, 304),
(5, 'M', 101, 5, 205, 305),
(6, 'F', 102, 6, 206, 306),
(7, 'M', 103, 7, 207, 307),
(8, 'F', 104, 8, 208, 308),
(9, 'M', 101, 9, 209, 309),
(10, 'F', 102, 10, 210, 310),
(11, 'M', 103, 11, 211, 311),
(12, 'F', 104, 12, 212, 312),
(13, 'M', 101, 13, 213, 313),
(14, 'F', 102, 14, 214, 314),
(15, 'M', 103, 15, 215, 315),
(16, 'F', 104, 16, 216, 316),
(17, 'M', 101, 17, 217, 317),
(18, 'F', 102, 18, 218, 318),
(19, 'M', 103, 19, 219, 319),
(20, 'F', 104, 20, 220, 320),
(21, 'M', 101, 21, 221, 321),
(22, 'F', 102, 22, 222, 322),
(23, 'M', 103, 23, 223, 323),
(24, 'F', 104, 24, 224, 324),
(25, 'M', 101, 25, 225, 325),
(26, 'F', 102, 26, 226, 326),
(27, 'M', 103, 27, 227, 327),
(28, 'F', 104, 28, 228, 328),
(29, 'M', 101, 29, 229, 329),
(30, 'F', 102, 30, 230, 330),
(31, 'M', 103, 31, 231, 331),
(32, 'F', 104, 32, 232, 332),
(33, 'M', 101, 33, 233, 333),
(34, 'F', 102, 34, 234, 334),
(35, 'M', 103, 35, 235, 335),
(36, 'F', 104, 36, 236, 336),
(37, 'M', 101, 37, 237, 337),
(38, 'F', 102, 38, 238, 338),
(39, 'M', 103, 39, 239, 339),
(40, 'F', 104, 40, 240, 340),
(41, 'M', 101, 41, 241, 341),
(42, 'F', 102, 42, 242, 342),
(43, 'M', 103, 43, 243, 343),
(44, 'F', 104, 44, 244, 344),
(45, 'M', 101, 45, 245, 345),
(46, 'F', 102, 46, 246, 346),
(47, 'M', 103, 47, 247, 347),
(48, 'F', 104, 48, 248, 348),
(49, 'M', 101, 49, 249, 349),
(50, 'F', 102, 50, 250, 350),
(51, 'M', 103, 51, 251, 351),
(52, 'F', 104, 52, 252, 352),
(53, 'M', 101, 53, 253, 353),
(54, 'F', 102, 54, 254, 354),
(55, 'M', 103, 55, 255, 355),
(56, 'F', 104, 56, 256, 356),
(57, 'M', 101, 57, 257, 357),
(58, 'F', 102, 58, 258, 358),
(59, 'M', 103, 59, 259, 359),
(60, 'F', 104, 60, 260, 360);
COMMIT;


sTART TRANSACTION;
USE `Farm`;
INSERT INTO land (land_id, land_type)
VALUES
(1, 'Agricultural'),
(2, 'Residential'),
(3, 'Commercial'),
(4, 'Industrial'),
(5, 'Pasture'),
(6, 'Forest'),
(7, 'Wetland'),
(8, 'Mountain'),
(9, 'Desert'),
(10, 'Grassland'),
(11, 'Floodplain'),
(12, 'Marsh'),
(13, 'Coastal'),
(14, 'Riverbank'),
(15, 'Hill'),
(16, 'Savannah'),
(17, 'Tundra'),
(18, 'Swamp'),
(19, 'Plains'),
(20, 'Steppe'),
(21, 'Vineyard'),
(22, 'Orchard'),
(23, 'Parkland'),
(24, 'Cropland'),
(25, 'Rangeland'),
(26, 'Wetlands'),
(27, 'Arable'),
(28, 'Grazing'),
(29, 'Pine Forest'),
(30, 'Deciduous Forest'),
(31, 'Tropical Rainforest'),
(32, 'Temperate Forest'),
(33, 'Boreal Forest'),
(34, 'Subtropical Forest'),
(35, 'Mangrove'),
(36, 'Cemetery'),
(37, 'Exurban'),
(38, 'Agricultural Land'),
(39, 'Mining Site'),
(40, 'Hydroelectric Dam'),
(41, 'Solar Farm'),
(42, 'Wind Farm'),
(43, 'Reservoir'),
(44, 'Fishing Area'),
(45, 'Pastureland'),
(46, 'Golf Course'),
(47, 'Nature Reserve'),
(48, 'Biofuel Plant'),
(49, 'Recreation Area'),
(50, 'Construction Site'),
(51, 'Research Area'),
(52, 'Urban Park'),
(53, 'Wildlife Habitat'),
(54, 'Greenhouse'),
(55, 'Botanical Garden'),
(56, 'Paddock'),
(57, 'Silo Area'),
(58, 'Livestock Grazing Area'),
(59, 'Aquaculture Area'),
(60, 'Agricultural Research Facility');
COMMIT;

sTART TRANSACTION;
USE `Farm`;
INSERT INTO warehouse (C_id, Amount)
VALUES
(1, 1000),
(2, 1500),
(3, 2000),
(4, 1800),
(5, 1200),
(6, 1700),
(7, 2200),
(8, 2500),
(9, 3000),
(10, 2700),
(11, 3200),
(12, 3500),
(13, 1400),
(14, 1900),
(15, 2300),
(16, 2100),
(17, 2400),
(18, 2600),
(19, 2800),
(20, 3100),
(21, 3300),
(22, 3400),
(23, 3600),
(24, 3700),
(25, 3800),
(26, 4000),
(27, 4100),
(28, 4200),
(29, 4300),
(30, 4400),
(31, 4500),
(32, 4600),
(33, 4700),
(34, 4800),
(35, 4900),
(36, 5000),
(37, 5100),
(38, 5200),
(39, 5300),
(40, 5400),
(41, 5500),
(42, 5600),
(43, 5700),
(44, 5800),
(45, 5900),
(46, 6000),
(47, 6100),
(48, 6200),
(49, 6300),
(50, 6400),
(51, 6500),
(52, 6600),
(53, 6700),
(54, 6800),
(55, 6900);
COMMIT;

sTART TRANSACTION;
USE `Farm`;
INSERT INTO Seeds (S_id, S_name, Category, Amount, Surid, land_id)
VALUES
(1, 'Wheat', 'Cereal', 1000, 101, 1),
(2, 'Corn', 'Cereal', 1200, 102, 2),
(3, 'Rice', 'Cereal', 1500, 103, 3),
(4, 'Barley', 'Cereal', 800, 104, 4),
(5, 'Soybean', 'Legume', 1300, 105, 5),
(6, 'Peas', 'Legume', 1100, 106, 6),
(7, 'Alfalfa', 'Forage', 950, 107, 7),
(8, 'Sugarcane', 'Sugar Crop', 2000, 108, 8),
(9, 'Cotton', 'Fiber Crop', 1500, 109, 9),
(10, 'Sunflower', 'Oilseed', 1800, 110, 10),
(11, 'Olives', 'Fruit', 2200, 111, 11),
(12, 'Apples', 'Fruit', 3000, 112, 12),
(13, 'Pears', 'Fruit', 2500, 113, 13),
(14, 'Grapes', 'Fruit', 3500, 114, 14),
(15, 'Tomatoes', 'Vegetable', 1200, 115, 15),
(16, 'Carrots', 'Vegetable', 1300, 116, 16),
(17, 'Potatoes', 'Vegetable', 2000, 117, 17),
(18, 'Cabbage', 'Vegetable', 1400, 118, 18),
(19, 'Lettuce', 'Vegetable', 1600, 119, 19),
(20, 'Peppers', 'Vegetable', 1700, 120, 20),
(21, 'Chili', 'Vegetable', 900, 121, 21),
(22, 'Garlic', 'Herb', 700, 122, 22),
(23, 'Onions', 'Vegetable', 2100, 123, 23),
(24, 'Ginger', 'Herb', 800, 124, 24),
(25, 'Lemon', 'Citrus', 2300, 125, 25),
(26, 'Oranges', 'Citrus', 2600, 126, 26),
(27, 'Mandarins', 'Citrus', 2400, 127, 27),
(28, 'Pineapple', 'Tropical Fruit', 3200, 128, 28),
(29, 'Bananas', 'Tropical Fruit', 2800, 129, 29),
(30, 'Papaya', 'Tropical Fruit', 1500, 130, 30),
(31, 'Avocado', 'Fruit', 2700, 131, 31),
(32, 'Mango', 'Tropical Fruit', 1900, 132, 32),
(33, 'Pine Nut', 'Nut', 1200, 133, 33),
(34, 'Almond', 'Nut', 1100, 134, 34),
(35, 'Cashew', 'Nut', 1000, 135, 35),
(36, 'Walnut', 'Nut', 800, 136, 36),
(37, 'Hazelnut', 'Nut', 600, 137, 37),
(38, 'Chestnut', 'Nut', 700, 138, 38),
(39, 'Pumpkin', 'Vegetable', 1500, 139, 39),
(40, 'Zucchini', 'Vegetable', 1600, 140, 40),
(41, 'Eggplant', 'Vegetable', 1800, 141, 41),
(42, 'Squash', 'Vegetable', 1400, 142, 42),
(43, 'Cucumber', 'Vegetable', 1700, 143, 43),
(44, 'Watermelon', 'Fruit', 2300, 144, 44),
(45, 'Melon', 'Fruit', 2100, 145, 45),
(46, 'Cantaloupe', 'Fruit', 2200, 146, 46),
(47, 'Strawberries', 'Berry', 1800, 147, 47),
(48, 'Blueberries', 'Berry', 1600, 148, 48),
(49, 'Raspberries', 'Berry', 1400, 149, 49),
(50, 'Blackberries', 'Berry', 1500, 150, 50),
(51, 'Cranberries', 'Berry', 1300, 151, 51),
(52, 'Gooseberries', 'Berry', 900, 152, 52),
(53, 'Mulberries', 'Berry', 800, 153, 53),
(54, 'Ginseng', 'Herb', 400, 154, 54),
(55, 'Lavender', 'Herb', 300, 155, 55),
(56, 'Rosemary', 'Herb', 500, 156, 56),
(57, 'Sage', 'Herb', 600, 157, 57),
(58, 'Thyme', 'Herb', 700, 158, 58),
(59, 'Oregano', 'Herb', 800, 159, 59),
(60, 'Basil', 'Herb', 1000, 160, 60);

COMMIT;
sTART TRANSACTION;
USE `Farm`;
INSERT INTO Fodder (Foid, Amount, Ma_id, Location, Cid)
VALUES
(1, 500, 1, 'New York', 1),
(2, 600, 2, 'Los Angeles', 2),
(3, 700, 3, 'Chicago', 3),
(4, 800, 4, 'Houston', 4),
(5, 900, 5, 'Phoenix', 5),
(6, 1000, 6, 'Philadelphia', 6),
(7, 1100, 7, 'San Antonio', 7),
(8, 1200, 8, 'San Diego', 8),
(9, 1300, 9, 'Dallas', 9),
(10, 1400, 10, 'San Jose', 10),
(11, 1500, 11, 'Austin', 11),
(12, 1600, 12, 'Jacksonville', 12),
(13, 1700, 13, 'Fort Worth', 13),
(14, 1800, 14, 'Columbus', 14),
(15, 1900, 15, 'Charlotte', 15),
(16, 2000, 16, 'Indianapolis', 16),
(17, 2100, 17, 'Seattle', 17),
(18, 2200, 18, 'Denver', 18),
(19, 2300, 19, 'Washington', 19),
(20, 2400, 20, 'Boston', 20),
(21, 2500, 21, 'El Paso', 21),
(22, 2600, 22, 'Detroit', 22),
(23, 2700, 23, 'Nashville', 23),
(24, 2800, 24, 'Portland', 24),
(25, 2900, 25, 'Memphis', 25),
(26, 3000, 26, 'Oklahoma City', 26),
(27, 3100, 27, 'Las Vegas', 27),
(28, 3200, 28, 'Louisville', 28),
(29, 3300, 29, 'Baltimore', 29),
(30, 3400, 30, 'Milwaukee', 30),
(31, 3500, 31, 'Albuquerque', 31),
(32, 3600, 32, 'Tucson', 32),
(33, 3700, 33, 'Fresno', 33),
(34, 3800, 34, 'Mesa', 34),
(35, 3900, 35, 'Sacramento', 35),
(36, 4000, 36, 'Kansas City', 36),
(37, 4100, 37, 'Long Beach', 37),
(38, 4200, 38, 'Atlanta', 38),
(39, 4300, 39, 'St. Louis', 39),
(40, 4400, 40, 'Riverside', 40),
(41, 4500, 41, 'Cleveland', 41),
(42, 4600, 42, 'Bakersfield', 42),
(43, 4700, 43, 'Tampa', 43),
(44, 4800, 44, 'New Orleans', 44),
(45, 4900, 45, 'Wichita', 45),
(46, 5000, 46, 'Arlington', 46),
(47, 5100, 47, 'Aurora', 47),
(48, 5200, 48, 'Beaumont', 48),
(49, 5300, 49, 'San Bernardino', 49),
(50, 5400, 50, 'Chula Vista', 50),
(51, 5500, 51, 'St. Paul', 51),
(52, 5600, 52, 'Laredo', 52),
(53, 5700, 53, 'Madison', 53),
(54, 5800, 54, 'Gilbert', 54),
(55, 5900, 55, 'Irving', 55),
(56, 6000, 56, 'Hialeah', 56),
(57, 6100, 57, 'Richmond', 57),
(58, 6200, 58, 'Chesapeake', 58),
(59, 6300, 59, 'Garland', 59),
(60, 6400, 60, 'Scottsdale', 60);

COMMIT;
sTART TRANSACTION;
USE `Farm`;
INSERT INTO anemal_prodact (id_prodacts, type_prodacts, Ma_id, w_location, C_id)
VALUES
(1, 'Fertilizer', 1, 'New York', 1),
(2, 'Seeds', 2, 'Los Angeles', 2),
(3, 'Pesticides', 3, 'Chicago', 3),
(4, 'Machinery Parts', 4, 'Houston', 4),
(5, 'Irrigation Tools', 5, 'Phoenix', 5),
(6, 'Harvest Equipment', 6, 'Philadelphia', 6),
(7, 'Greenhouse Materials', 7, 'San Antonio', 7),
(8, 'Farming Tools', 8, 'San Diego', 8),
(9, 'Soil Testing Kits', 9, 'Dallas', 9),
(10, 'Animal Feed', 10, 'San Jose', 10),
(11, 'Organic Fertilizer', 11, 'Austin', 11),
(12, 'Tractor Accessories', 12, 'Jacksonville', 12),
(13, 'Crop Protection', 13, 'Fort Worth', 13),
(14, 'Harvest Bins', 14, 'Columbus', 14),
(15, 'Water Pumps', 15, 'Charlotte', 15),
(16, 'Compost', 16, 'Indianapolis', 16),
(17, 'Farm Fencing', 17, 'Seattle', 17),
(18, 'Plant Pots', 18, 'Denver', 18),
(19, 'Herbicide', 19, 'Washington', 19),
(20, 'Sprinkler Systems', 20, 'Boston', 20),
(21, 'Hay', 21, 'El Paso', 21),
(22, 'Shovels', 22, 'Detroit', 22),
(23, 'Tractor Tires', 23, 'Nashville', 23),
(24, 'Garden Nets', 24, 'Portland', 24),
(25, 'Animal Care Kits', 25, 'Memphis', 25),
(26, 'Drip Irrigation', 26, 'Oklahoma City', 26),
(27, 'Safety Gear', 27, 'Las Vegas', 27),
(28, 'Farm Lights', 28, 'Louisville', 28),
(29, 'Weed Killer', 29, 'Baltimore', 29),
(30, 'Crop Storage Bags', 30, 'Milwaukee', 30),
(31, 'Seedlings', 31, 'Albuquerque', 31),
(32, 'Tractor Fuel', 32, 'Tucson', 32),
(33, 'Solar Panels', 33, 'Fresno', 33),
(34, 'Compost Bins', 34, 'Mesa', 34),
(35, 'Beehives', 35, 'Sacramento', 35),
(36, 'Farming Manuals', 36, 'Kansas City', 36),
(37, 'Wind Turbines', 37, 'Long Beach', 37),
(38, 'Crop Transport Boxes', 38, 'Atlanta', 38),
(39, 'Farm Vehicles', 39, 'St. Louis', 39),
(40, 'Livestock Care Kits', 40, 'Riverside', 40),
(41, 'Worm Compost', 41, 'Cleveland', 41),
(42, 'Aquaponic Supplies', 42, 'Bakersfield', 42),
(43, 'Fish Food', 43, 'Tampa', 43),
(44, 'Egg Incubators', 44, 'New Orleans', 44),
(45, 'Greenhouse Lights', 45, 'Wichita', 45),
(46, 'Irrigation Filters', 46, 'Arlington', 46),
(47, 'Farm Tents', 47, 'Aurora', 47),
(48, 'Crop Sensors', 48, 'Beaumont', 48),
(49, 'Water Tanks', 49, 'San Bernardino', 49),
(50, 'Seed Storage', 50, 'Chula Vista', 50),
(51, 'Animal Vaccines', 51, 'St. Paul', 51),
(52, 'Bio Pesticides', 52, 'Laredo', 52),
(53, 'Solar Dryers', 53, 'Madison', 53),
(54, 'Irrigation Nozzles', 54, 'Gilbert', 54),
(55, 'Bio Fertilizers', 55, 'Irving', 55),
(56, 'Hydroponic Trays', 56, 'Hialeah', 56),
(57, 'Windbreak Nets', 57, 'Richmond', 57),
(58, 'Harvest Scales', 58, 'Chesapeake', 58),
(59, 'Compost Starters', 59, 'Garland', 59),
(60, 'Rain Gauges', 60, 'Scottsdale', 60);

COMMIT;

sTART TRANSACTION;
USE `Farm`;
INSERT INTO w_location (c_id, w_location)
VALUES
(1, 'New York'),
(2, 'Los Angeles'),
(3, 'Chicago'),
(4, 'Houston'),
(5, 'Phoenix'),
(6, 'Philadelphia'),
(7, 'San Antonio'),
(8, 'San Diego'),
(9, 'Dallas'),
(10, 'San Jose'),
(11, 'Austin'),
(12, 'Jacksonville'),
(13, 'Fort Worth'),
(14, 'Columbus'),
(15, 'Charlotte'),
(16, 'Indianapolis'),
(17, 'Seattle'),
(18, 'Denver'),
(19, 'Washington'),
(20, 'Boston'),
(21, 'El Paso'),
(22, 'Detroit'),
(23, 'Nashville'),
(24, 'Portland'),
(25, 'Memphis'),
(26, 'Oklahoma City'),
(27, 'Las Vegas'),
(28, 'Louisville'),
(29, 'Baltimore'),
(30, 'Milwaukee'),
(31, 'Albuquerque'),
(32, 'Tucson'),
(33, 'Fresno'),
(34, 'Mesa'),
(35, 'Sacramento'),
(36, 'Kansas City'),
(37, 'Atlanta'),
(38, 'Miami'),
(39, 'Raleigh'),
(40, 'Omaha'),
(41, 'Long Beach'),
(42, 'Virginia Beach'),
(43, 'Oakland'),
(44, 'Minneapolis'),
(45, 'Tulsa'),
(46, 'Arlington'),
(47, 'Tampa'),
(48, 'New Orleans'),
(49, 'Wichita'),
(50, 'Bakersfield'),
(51, 'Aurora'),
(52, 'Anaheim'),
(53, 'Santa Ana'),
(54, 'Corpus Christi'),
(55, 'Riverside');
COMMIT;

sTART TRANSACTION;
USE `Farm`;
INSERT INTO pesticide (P_id, P_name, Category, Amount, Sup_id)
VALUES
(1, 'Herbicide A', 'Weed Control', 100, 10),
(2, 'Insecticide B', 'Pest Control', 200, 11),
(3, 'Fungicide C', 'Fungal Control', 150, 12),
(4, 'Rodenticide D', 'Rodent Control', 180, 13),
(5, 'Herbicide E', 'Weed Control', 120, 14),
(6, 'Insecticide F', 'Pest Control', 170, 15),
(7, 'Fungicide G', 'Fungal Control', 220, 16),
(8, 'Rodenticide H', 'Rodent Control', 250, 17),
(9, 'Herbicide I', 'Weed Control', 300, 18),
(10, 'Insecticide J', 'Pest Control', 270, 19),
(11, 'Fungicide K', 'Fungal Control', 320, 20),
(12, 'Rodenticide L', 'Rodent Control', 350, 21),
(13, 'Herbicide M', 'Weed Control', 140, 22),
(14, 'Insecticide N', 'Pest Control', 190, 23),
(15, 'Fungicide O', 'Fungal Control', 230, 24),
(16, 'Rodenticide P', 'Rodent Control', 210, 25),
(17, 'Herbicide Q', 'Weed Control', 240, 26),
(18, 'Insecticide R', 'Pest Control', 260, 27),
(19, 'Fungicide S', 'Fungal Control', 280, 28),
(20, 'Rodenticide T', 'Rodent Control', 310, 29),
(21, 'Herbicide U', 'Weed Control', 330, 30),
(22, 'Insecticide V', 'Pest Control', 340, 31),
(23, 'Fungicide W', 'Fungal Control', 360, 32),
(24, 'Rodenticide X', 'Rodent Control', 370, 33),
(25, 'Herbicide Y', 'Weed Control', 380, 34),
(26, 'Insecticide Z', 'Pest Control', 400, 35),
(27, 'Fungicide AA', 'Fungal Control', 410, 36),
(28, 'Rodenticide BB', 'Rodent Control', 420, 37),
(29, 'Herbicide CC', 'Weed Control', 430, 38),
(30, 'Insecticide DD', 'Pest Control', 440, 39),
(31, 'Fungicide EE', 'Fungal Control', 450, 40),
(32, 'Rodenticide FF', 'Rodent Control', 460, 41),
(33, 'Herbicide GG', 'Weed Control', 470, 42),
(34, 'Insecticide HH', 'Pest Control', 480, 43),
(35, 'Fungicide II', 'Fungal Control', 490, 44),
(36, 'Rodenticide JJ', 'Rodent Control', 500, 45),
(37, 'Herbicide KK', 'Weed Control', 510, 46),
(38, 'Insecticide LL', 'Pest Control', 520, 47),
(39, 'Fungicide MM', 'Fungal Control', 530, 48),
(40, 'Rodenticide NN', 'Rodent Control', 540, 49),
(41, 'Herbicide OO', 'Weed Control', 550, 50),
(42, 'Insecticide PP', 'Pest Control', 560, 51),
(43, 'Fungicide QQ', 'Fungal Control', 570, 52),
(44, 'Rodenticide RR', 'Rodent Control', 580, 53),
(45, 'Herbicide SS', 'Weed Control', 590, 54),
(46, 'Insecticide TT', 'Pest Control', 600, 55),
(47, 'Fungicide UU', 'Fungal Control', 610, 56),
(48, 'Rodenticide VV', 'Rodent Control', 620, 57),
(49, 'Herbicide WW', 'Weed Control', 630, 58),
(50, 'Insecticide XX', 'Pest Control', 640, 59),
(51, 'Fungicide YY', 'Fungal Control', 650, 60),
(52, 'Rodenticide ZZ', 'Rodent Control', 660, 61),
(53, 'Herbicide AAA', 'Weed Control', 670, 62),
(54, 'Insecticide BBB', 'Pest Control', 680, 63),
(55, 'Fungicide CCC', 'Fungal Control', 690, 64);
COMMIT;

sTART TRANSACTION;
USE `Farm`;
INSERT INTO crops (C_id, C_name, C_category, Amount, F_id, Ma_id)
VALUES
('C001', 'Wheat', 'Grain', 1200, 1, 101),
('C002', 'Rice', 'Grain', 1400, 2, 102),
('C003', 'Corn', 'Grain', 1600, 3, 103),
('C004', 'Soybean', 'Legume', 1800, 4, 104),
('C005', 'Barley', 'Grain', 1500, 1, 101),
('C006', 'Sugarcane', 'Cash Crop', 1900, 2, 102),
('C007', 'Cotton', 'Cash Crop', 2100, 3, 103),
('C008', 'Potato', 'Vegetable', 1700, 4, 104),
('C009', 'Tomato', 'Vegetable', 1300, 1, 101),
('C010', 'Onion', 'Vegetable', 1200, 2, 102),
('C011', 'Carrot', 'Vegetable', 1400, 3, 103),
('C012', 'Pepper', 'Vegetable', 1600, 4, 104),
('C013', 'Garlic', 'Herb', 1100, 1, 101),
('C014', 'Ginger', 'Herb', 1300, 2, 102),
('C015', 'Mint', 'Herb', 1500, 3, 103),
('C016', 'Lettuce', 'Leafy', 1000, 4, 104),
('C017', 'Spinach', 'Leafy', 1100, 1, 101),
('C018', 'Cabbage', 'Leafy', 1200, 2, 102),
('C019', 'Apple', 'Fruit', 1400, 3, 103),
('C020', 'Banana', 'Fruit', 1600, 4, 104),
('C021', 'Mango', 'Fruit', 1500, 1, 101),
('C022', 'Orange', 'Fruit', 1700, 2, 102),
('C023', 'Papaya', 'Fruit', 1800, 3, 103),
('C024', 'Peach', 'Fruit', 1900, 4, 104),
('C025', 'Grapes', 'Fruit', 2000, 1, 101),
('C026', 'Pineapple', 'Fruit', 2100, 2, 102),
('C027', 'Strawberry', 'Fruit', 2200, 3, 103),
('C028', 'Blueberry', 'Fruit', 2300, 4, 104),
('C029', 'Raspberry', 'Fruit', 2400, 1, 101),
('C030', 'Cherry', 'Fruit', 2500, 2, 102),
('C031', 'Melon', 'Fruit', 2600, 3, 103),
('C032', 'Pumpkin', 'Vegetable', 2700, 4, 104),
('C033', 'Cucumber', 'Vegetable', 2800, 1, 101),
('C034', 'Zucchini', 'Vegetable', 2900, 2, 102),
('C035', 'Radish', 'Vegetable', 3000, 3, 103),
('C036', 'Beetroot', 'Vegetable', 3100, 4, 104),
('C037', 'Parsley', 'Herb', 3200, 1, 101),
('C038', 'Basil', 'Herb', 3300, 2, 102),
('C039', 'Thyme', 'Herb', 3400, 3, 103),
('C040', 'Rosemary', 'Herb', 3500, 4, 104),
('C041', 'Chili', 'Spice', 3600, 1, 101),
('C042', 'Turmeric', 'Spice', 3700, 2, 102),
('C043', 'Clove', 'Spice', 3800, 3, 103),
('C044', 'Cinnamon', 'Spice', 3900, 4, 104),
('C045', 'Cardamom', 'Spice', 4000, 1, 101),
('C046', 'Peppercorn', 'Spice', 4100, 2, 102),
('C047', 'Oregano', 'Herb', 4200, 3, 103),
('C048', 'Dill', 'Herb', 4300, 4, 104),
('C049', 'Chives', 'Herb', 4400, 1, 101),
('C050', 'Bay Leaf', 'Herb', 4500, 2, 102),
('C051', 'Mustard', 'Seed', 4600, 3, 103),
('C052', 'Fenugreek', 'Seed', 4700, 4, 104);
COMMIT;

sTART TRANSACTION;
USE `Farm`;
INSERT INTO fodder (Fo_id, Amount, Ma_id, Location, C_id)
VALUES
(1, 500, 101, 'North Storage', 1),
(2, 600, 102, 'East Storage', 2),
(3, 700, 103, 'West Storage', 3),
(4, 550, 104, 'Central Storage', 4),
(5, 620, 105, 'South Storage', 5),
(6, 580, 101, 'North Storage', 6),
(7, 490, 102, 'East Storage', 7),
(8, 520, 103, 'West Storage', 8),
(9, 610, 104, 'Central Storage', 9),
(10, 570, 105, 'South Storage', 10),
(11, 680, 101, 'North Storage', 11),
(12, 590, 102, 'East Storage', 12),
(13, 600, 103, 'West Storage', 13),
(14, 510, 104, 'Central Storage', 14),
(15, 530, 105, 'South Storage', 15),
(16, 540, 101, 'North Storage', 16),
(17, 620, 102, 'East Storage', 17),
(18, 560, 103, 'West Storage', 18),
(19, 490, 104, 'Central Storage', 19),
(20, 570, 105, 'South Storage', 20),
(21, 600, 101, 'North Storage', 21),
(22, 610, 102, 'East Storage', 22),
(23, 580, 103, 'West Storage', 23),
(24, 540, 104, 'Central Storage', 24),
(25, 550, 105, 'South Storage', 25),
(26, 590, 101, 'North Storage', 26),
(27, 560, 102, 'East Storage', 27),
(28, 530, 103, 'West Storage', 28),
(29, 540, 104, 'Central Storage', 29),
(30, 600, 105, 'South Storage', 30),
(31, 620, 101, 'North Storage', 31),
(32, 580, 102, 'East Storage', 32),
(33, 610, 103, 'West Storage', 33),
(34, 520, 104, 'Central Storage', 34),
(35, 510, 105, 'South Storage', 35),
(36, 550, 101, 'North Storage', 36),
(37, 560, 102, 'East Storage', 37),
(38, 530, 103, 'West Storage', 38),
(39, 580, 104, 'Central Storage', 39),
(40, 540, 105, 'South Storage', 40),
(41, 610, 101, 'North Storage', 41),
(42, 590, 102, 'East Storage', 42),
(43, 620, 103, 'West Storage', 43),
(44, 510, 104, 'Central Storage', 44),
(45, 540, 105, 'South Storage', 45),
(46, 550, 101, 'North Storage', 46),
(47, 570, 102, 'East Storage', 47),
(48, 580, 103, 'West Storage', 48),
(49, 600, 104, 'Central Storage', 49),
(50, 590, 105, 'South Storage', 50);
COMMIT;

sTART TRANSACTION;
USE `Farm`;
INSERT INTO supplier (S_id, S_name, S_sex, S_address, Phone, Email)
VALUES
(1, 'John Smith', 'M', '123 Elm St', 1234567890, 'john.smith@example.com'),
(2, 'Emily Johnson', 'F', '456 Oak Ave', 1234567891, 'emily.johnson@example.com'),
(3, 'Michael Brown', 'M', '789 Pine Rd', 1234567892, 'michael.brown@example.com'),
(4, 'Sarah Davis', 'F', '321 Maple St', 1234567893, 'sarah.davis@example.com'),
(5, 'David Wilson', 'M', '654 Cedar Ave', 1234567894, 'david.wilson@example.com'),
(6, 'Laura Moore', 'F', '987 Birch Rd', 1234567895, 'laura.moore@example.com'),
(7, 'James Taylor', 'M', '159 Spruce St', 1234567896, 'james.taylor@example.com'),
(8, 'Anna Anderson', 'F', '753 Willow Ave', 1234567897, 'anna.anderson@example.com'),
(9, 'Robert Thomas', 'M', '456 Aspen Rd', 1234567898, 'robert.thomas@example.com'),
(10, 'Patricia Jackson', 'F', '678 Cherry St', 1234567899, 'patricia.jackson@example.com'),
(11, 'Daniel White', 'M', '123 Walnut St', 1234567900, 'daniel.white@example.com'),
(12, 'Karen Harris', 'F', '456 Dogwood Ave', 1234567901, 'karen.harris@example.com'),
(13, 'Steven Martin', 'M', '789 Sycamore Rd', 1234567902, 'steven.martin@example.com'),
(14, 'Sophia Martinez', 'F', '321 Chestnut St', 1234567903, 'sophia.martinez@example.com'),
(15, 'Mark Garcia', 'M', '654 Poplar Ave', 1234567904, 'mark.garcia@example.com'),
(16, 'Lisa Rodriguez', 'F', '987 Magnolia Rd', 1234567905, 'lisa.rodriguez@example.com'),
(17, 'Brian Clark', 'M', '159 Palm St', 1234567906, 'brian.clark@example.com'),
(18, 'Megan Lewis', 'F', '753 Cypress Ave', 1234567907, 'megan.lewis@example.com'),
(19, 'Kevin Walker', 'M', '456 Hickory Rd', 1234567908, 'kevin.walker@example.com'),
(20, 'Emma Hall', 'F', '678 Alder St', 1234567909, 'emma.hall@example.com'),
(21, 'Ethan Young', 'M', '123 Redwood St', 1234567910, 'ethan.young@example.com'),
(22, 'Olivia King', 'F', '456 Maplewood Ave', 1234567911, 'olivia.king@example.com'),
(23, 'Jacob Wright', 'M', '789 Sandalwood Rd', 1234567912, 'jacob.wright@example.com'),
(24, 'Ava Scott', 'F', '321 Hawthorn St', 1234567913, 'ava.scott@example.com'),
(25, 'Henry Green', 'M', '654 Baywood Ave', 1234567914, 'henry.green@example.com'),
(26, 'Isabella Adams', 'F', '987 Redwood Rd', 1234567915, 'isabella.adams@example.com'),
(27, 'Joshua Nelson', 'M', '159 Sequoia St', 1234567916, 'joshua.nelson@example.com'),
(28, 'Grace Carter', 'F', '753 Fir Ave', 1234567917, 'grace.carter@example.com'),
(29, 'Ryan Perez', 'M', '456 Douglas Rd', 1234567918, 'ryan.perez@example.com'),
(30, 'Zoe Murphy', 'F', '678 Redwood St', 1234567919, 'zoe.murphy@example.com'),
(31, 'Noah Reed', 'M', '123 Aspen Ave', 1234567920, 'noah.reed@example.com'),
(32, 'Lily Bailey', 'F', '456 Pinewood Rd', 1234567921, 'lily.bailey@example.com'),
(33, 'Mason Cooper', 'M', '789 Willow St', 1234567922, 'mason.cooper@example.com'),
(34, 'Ella Rivera', 'F', '321 Redwood Ave', 1234567923, 'ella.rivera@example.com'),
(35, 'Lucas Richardson', 'M', '654 Cedarwood Rd', 1234567924, 'lucas.richardson@example.com'),
(36, 'Chloe Watson', 'F', '987 Firwood St', 1234567925, 'chloe.watson@example.com'),
(37, 'Alexander Brooks', 'M', '159 Hickory Ave', 1234567926, 'alexander.brooks@example.com'),
(38, 'Victoria Kelly', 'F', '753 Elmwood Rd', 1234567927, 'victoria.kelly@example.com'),
(39, 'Samuel Howard', 'M', '456 Sprucewood St', 1234567928, 'samuel.howard@example.com'),
(40, 'Abigail Ward', 'F', '678 Palmwood Ave', 1234567929, 'abigail.ward@example.com'),
(41, 'Nathan Torres', 'M', '123 Poplarwood Rd', 1234567930, 'nathan.torres@example.com'),
(42, 'Sofia Lee', 'F', '456 Redwoodwood St', 1234567931, 'sofia.lee@example.com'),
(43, 'Owen Phillips', 'M', '789 Cherrywood Ave', 1234567932, 'owen.phillips@example.com'),
(44, 'Amelia Bennett', 'F', '321 Dogwoodwood Rd', 1234567933, 'amelia.bennett@example.com'),
(45, 'Jack Evans', 'M', '654 Maplewood St', 1234567934, 'jack.evans@example.com'),
(46, 'Mia Sanchez', 'F', '987 Pinewood Ave', 1234567935, 'mia.sanchez@example.com'),
(47, 'Logan Gonzalez', 'M', '159 Cedarwood Rd', 1234567936, 'logan.gonzalez@example.com'),
(48, 'Hannah Ramirez', 'F', '753 Birchwood St', 1234567937, 'hannah.ramirez@example.com'),
(49, 'William Edwards', 'M', '456 Alderwood Ave', 1234567938, 'william.edwards@example.com'),
(50, 'Natalie Torres', 'F', '678 Chestnutwood Rd', 1234567939, 'natalie.torres@example.com');
COMMIT;
sTART TRANSACTION;
USE `Farm`;
INSERT INTO merchant (M_id, M_name, M_sex, M_bank_account, Phone, Email, C_id)
VALUES
(1, 'John Smith', 'M', 123456, 1234567890, 'john.smith@example.com', 1),
(2, 'Emily Johnson', 'F', 234567, 1234567891, 'emily.johnson@example.com', 2),
(3, 'Michael Brown', 'M', 345678, 1234567892, 'michael.brown@example.com', 3),
(4, 'Sarah Davis', 'F', 456789, 1234567893, 'sarah.davis@example.com', 1),
(5, 'David Wilson', 'M', 567890, 1234567894, 'david.wilson@example.com', 2),
(6, 'Laura Moore', 'F', 678901, 1234567895, 'laura.moore@example.com', 3),
(7, 'James Taylor', 'M', 789012, 1234567896, 'james.taylor@example.com', 1),
(8, 'Anna Anderson', 'F', 890123, 1234567897, 'anna.anderson@example.com', 2),
(9, 'Robert Thomas', 'M', 901234, 1234567898, 'robert.thomas@example.com', 3),
(10, 'Patricia Jackson', 'F', 112233, 1234567899, 'patricia.jackson@example.com', 1),
(11, 'Daniel White', 'M', 223344, 1234567900, 'daniel.white@example.com', 2),
(12, 'Karen Harris', 'F', 334455, 1234567901, 'karen.harris@example.com', 3),
(13, 'Steven Martin', 'M', 445566, 1234567902, 'steven.martin@example.com', 1),
(14, 'Sophia Martinez', 'F', 556677, 1234567903, 'sophia.martinez@example.com', 2),
(15, 'Mark Garcia', 'M', 667788, 1234567904, 'mark.garcia@example.com', 3),
(16, 'Lisa Rodriguez', 'F', 778899, 1234567905, 'lisa.rodriguez@example.com', 1),
(17, 'Brian Clark', 'M', 889900, 1234567906, 'brian.clark@example.com', 2),
(18, 'Megan Lewis', 'F', 990011, 1234567907, 'megan.lewis@example.com', 3),
(19, 'Kevin Walker', 'M', 101112, 1234567908, 'kevin.walker@example.com', 1),
(20, 'Emma Hall', 'F', 121314, 1234567909, 'emma.hall@example.com', 2),
(21, 'Ethan Young', 'M', 131415, 1234567910, 'ethan.young@example.com', 3),
(22, 'Olivia King', 'F', 141516, 1234567911, 'olivia.king@example.com', 1),
(23, 'Jacob Wright', 'M', 151617, 1234567912, 'jacob.wright@example.com', 2),
(24, 'Ava Scott', 'F', 161718, 1234567913, 'ava.scott@example.com', 3),
(25, 'Henry Green', 'M', 171819, 1234567914, 'henry.green@example.com', 1),
(26, 'Isabella Adams', 'F', 181920, 1234567915, 'isabella.adams@example.com', 2),
(27, 'Joshua Nelson', 'M', 192021, 1234567916, 'joshua.nelson@example.com', 3),
(28, 'Grace Carter', 'F', 202122, 1234567917, 'grace.carter@example.com', 1),
(29, 'Ryan Perez', 'M', 212223, 1234567918, 'ryan.perez@example.com', 2),
(30, 'Zoe Murphy', 'F', 222324, 1234567919, 'zoe.murphy@example.com', 3),
(31, 'Noah Reed', 'M', 232425, 1234567920, 'noah.reed@example.com', 1),
(32, 'Lily Bailey', 'F', 242526, 1234567921, 'lily.bailey@example.com', 2),
(33, 'Mason Cooper', 'M', 252627, 1234567922, 'mason.cooper@example.com', 3),
(34, 'Ella Rivera', 'F', 262728, 1234567923, 'ella.rivera@example.com', 1),
(35, 'Lucas Richardson', 'M', 272829, 1234567924, 'lucas.richardson@example.com', 2),
(36, 'Chloe Watson', 'F', 282930, 1234567925, 'chloe.watson@example.com', 3),
(37, 'Alexander Brooks', 'M', 293031, 1234567926, 'alexander.brooks@example.com', 1),
(38, 'Victoria Kelly', 'F', 303132, 1234567927, 'victoria.kelly@example.com', 2),
(39, 'Samuel Howard', 'M', 313233, 1234567928, 'samuel.howard@example.com', 3),
(40, 'Abigail Ward', 'F', 323334, 1234567929, 'abigail.ward@example.com', 1),
(41, 'Nathan Torres', 'M', 333435, 1234567930, 'nathan.torres@example.com', 2),
(42, 'Sofia Lee', 'F', 343536, 1234567931, 'sofia.lee@example.com', 3),
(43, 'Owen Phillips', 'M', 353637, 1234567932, 'owen.phillips@example.com', 1),
(44, 'Amelia Bennett', 'F', 363738, 1234567933, 'amelia.bennett@example.com', 2),
(45, 'Jack Evans', 'M', 373839, 1234567934, 'jack.evans@example.com', 3),
(46, 'Mia Sanchez', 'F', 383940, 1234567935, 'mia.sanchez@example.com', 1),
(47, 'Logan Gonzalez', 'M', 394041, 1234567936, 'logan.gonzalez@example.com', 2),
(48, 'Hannah Ramirez', 'F', 404142, 1234567937, 'hannah.ramirez@example.com', 3),
(49, 'William Edwards', 'M', 414243, 1234567938, 'william.edwards@example.com', 1),
(50, 'Natalie Torres', 'F', 424344, 1234567939, 'natalie.torres@example.com', 2);
COMMIT;
sTART TRANSACTION;
USE `Farm`;
INSERT INTO collected_from (M_id, F_id, B_id)
VALUES
(1, 101, 1),
(2, 102, 2),
(3, 103, 3),
(4, 104, 4),
(5, 105, 5),
(6, 106, 6),
(7, 107, 7),
(8, 108, 8),
(9, 109, 9),
(10, 110, 10),
(11, 111, 11),
(12, 112, 12),
(13, 113, 13),
(14, 114, 14),
(15, 115, 15),
(16, 116, 16),
(17, 117, 17),
(18, 118, 18),
(19, 119, 19),
(20, 120, 20),
(21, 121, 21),
(22, 122, 22),
(23, 123, 23),
(24, 124, 24),
(25, 125, 25),
(26, 126, 26),
(27, 127, 27),
(28, 128, 28),
(29, 129, 29),
(30, 130, 30),
(31, 131, 31),
(32, 132, 32),
(33, 133, 33),
(34, 134, 34),
(35, 135, 35),
(36, 136, 36),
(37, 137, 37),
(38, 138, 38),
(39, 139, 39),
(40, 140, 40),
(41, 141, 41),
(42, 142, 42),
(43, 143, 43),
(44, 144, 44),
(45, 145, 45),
(46, 146, 46),
(47, 147, 47),
(48, 148, 48),
(49, 149, 49),
(50, 150, 50);
COMMIT;
sTART TRANSACTION;
USE `Farm`;
INSERT INTO money_collected (F_id, B_id, Date_of_coll)
VALUES
(101, 1, '2024-01-01'),
(102, 2, '2024-01-05'),
(103, 3, '2024-01-10'),
(104, 4, '2024-01-15'),
(105, 5, '2024-01-20'),
(106, 6, '2024-01-25'),
(107, 7, '2024-01-30'),
(108, 8, '2024-02-01'),
(109, 9, '2024-02-05'),
(110, 10, '2024-02-10'),
(111, 11, '2024-02-15'),
(112, 12, '2024-02-20'),
(113, 13, '2024-02-25'),
(114, 14, '2024-03-01'),
(115, 15, '2024-03-05'),
(116, 16, '2024-03-10'),
(117, 17, '2024-03-15'),
(118, 18, '2024-03-20'),
(119, 19, '2024-03-25'),
(120, 20, '2024-03-30'),
(121, 21, '2024-04-01'),
(122, 22, '2024-04-05'),
(123, 23, '2024-04-10'),
(124, 24, '2024-04-15'),
(125, 25, '2024-04-20'),
(126, 26, '2024-04-25'),
(127, 27, '2024-04-30'),
(128, 28, '2024-05-01'),
(129, 29, '2024-05-05'),
(130, 30, '2024-05-10'),
(131, 31, '2024-05-15'),
(132, 32, '2024-05-20'),
(133, 33, '2024-05-25'),
(134, 34, '2024-05-30'),
(135, 35, '2024-06-01'),
(136, 36, '2024-06-05'),
(137, 37, '2024-06-10'),
(138, 38, '2024-06-15'),
(139, 39, '2024-06-20'),
(140, 40, '2024-06-25'),
(141, 41, '2024-06-30'),
(142, 42, '2024-07-01'),
(143, 43, '2024-07-05'),
(144, 44, '2024-07-10'),
(145, 45, '2024-07-15'),
(146, 46, '2024-07-20'),
(147, 47, '2024-07-25'),
(148, 48, '2024-07-30'),
(149, 49, '2024-08-01'),
(150, 50, '2024-08-05');
COMMIT;
sTART TRANSACTION;
USE `Farm`;
INSERT INTO Bank (B_id, B_name)
VALUES
(1, 'Bank of America'),
(2, 'Chase Bank'),
(3, 'Wells Fargo'),
(4, 'Citibank'),
(5, 'HSBC'),
(6, 'Barclays'),
(7, 'Santander'),
(8, 'Goldman Sachs'),
(9, 'Morgan Stanley'),
(10, 'Deutsche Bank'),
(11, 'UBS'),
(12, 'Bank of England'),
(13, 'Royal Bank of Canada'),
(14, 'Toronto Dominion Bank'),
(15, 'Bank of Montreal'),
(16, 'Credit Suisse'),
(17, 'Scotiabank'),
(18, 'BNP Paribas'),
(19, 'Lloyds Bank'),
(20, 'RBC'),
(21, 'ING Bank'),
(22, 'Nomura'),
(23, 'Macquarie Bank'),
(24, 'Standard Chartered'),
(25, 'Danske Bank'),
(26, 'Raiffeisen Bank'),
(27, 'Unicredit'),
(28, 'National Australia Bank'),
(29, 'Westpac Banking Corporation'),
(30, 'ANZ Bank'),
(31, 'Bank of New York Mellon'),
(32, 'Credit Agricole'),
(33, 'China Construction Bank'),
(34, 'Agricultural Bank of China'),
(35, 'Industrial and Commercial Bank of China'),
(36, 'Bank of Tokyo-Mitsubishi UFJ'),
(37, 'Sumitomo Mitsui Trust Bank'),
(38, 'State Bank of India'),
(39, 'Bank of China'),
(40, 'Citi Private Bank'),
(41, 'Pictet & Cie'),
(42, 'Bank of India'),
(43, 'Wells Fargo Private Bank'),
(44, 'JPMorgan Chase'),
(45, 'Royal Bank of Scotland'),
(46, 'First Republic Bank'),
(47, 'Fifth Third Bank'),
(48, 'U.S. Bank'),
(49, 'Regions Bank'),
(50, 'KeyBank');
COMMIT;

sTART TRANSACTION;
USE `Farm`;
INSERT INTO Bank_location (B_id, Blocation)
VALUES
(1, 'New York, USA'),
(2, 'London, UK'),
(3, 'San Francisco, USA'),
(4, 'Paris, France'),
(5, 'Hong Kong, China'),
(6, 'Berlin, Germany'),
(7, 'Madrid, Spain'),
(8, 'Sydney, Australia'),
(9, 'Tokyo, Japan'),
(10, 'Zurich, Switzerland'),
(11, 'Toronto, Canada'),
(12, 'Montreal, Canada'),
(13, 'Singapore, Singapore'),
(14, 'Dubai, UAE'),
(15, 'Mumbai, India'),
(16, 'Los Angeles, USA'),
(17, 'Chicago, USA'),
(18, 'Amsterdam, Netherlands'),
(19, 'Rome, Italy'),
(20, 'Moscow, Russia'),
(21, 'Dubai, UAE'),
(22, 'Geneva, Switzerland'),
(23, 'Seoul, South Korea'),
(24, 'Vienna, Austria'),
(25, 'Stockholm, Sweden'),
(26, 'Oslo, Norway'),
(27, 'Copenhagen, Denmark'),
(28, 'Kuala Lumpur, Malaysia'),
(29, 'Jakarta, Indonesia'),
(30, 'Lagos, Nigeria'),
(31, 'Cape Town, South Africa'),
(32, 'Buenos Aires, Argentina'),
(33, 'Lagos, Nigeria'),
(34, 'Lima, Peru'),
(35, 'Bogotá, Colombia'),
(36, 'Sao Paulo, Brazil'),
(37, 'Mexico City, Mexico'),
(38, 'Chicago, USA'),
(39, 'Bangkok, Thailand'),
(40, 'Warsaw, Poland'),
(41, 'Johannesburg, South Africa'),
(42, 'Madrid, Spain'),
(43, 'Paris, France'),
(44, 'Barcelona, Spain'),
(45, 'Hong Kong, China'),
(46, 'Los Angeles, USA'),
(47, 'Paris, France'),
(48, 'London, UK'),
(49, 'Stockholm, Sweden'),
(50, 'Berlin, Germany');
COMMIT;

